import { z } from "zod";

/**
 * Conventional Commit types standardizing agent code modifications.
 */
export const ConventionalCommitTypeSchema = z.enum([
  "feat",
  "fix",
  "refactor",
  "test",
  "docs",
  "style",
  "perf",
  "chore",
  "build",
  "ci",
]);
export type ConventionalCommitType = z.infer<
  typeof ConventionalCommitTypeSchema
>;

/**
 * Isolated Git worktree execution context.
 */
export const WorktreeContextSchema = z.object({
  taskId: z.string().uuid("Task ID must be a valid UUID"),
  targetRepoPath: z.string().min(1, "Target repository path is required"),
  worktreePath: z.string().min(1, "Isolated worktree path is required"),
  baseCommitHash: z.string().min(7, "Base commit hash is required"),
  branchName: z.string().min(1, "Branch name is required"),
  status: z
    .enum(["active", "merged", "rolled_back", "pruned"])
    .default("active"),
  createdAt: z.number().int().nonnegative().default(() => Date.now()),
});
export type WorktreeContext = z.infer<typeof WorktreeContextSchema>;

/**
 * Metadata for atomic semantic Conventional Commits generated by agents.
 */
export const SemanticCommitMetaSchema = z.object({
  type: ConventionalCommitTypeSchema,
  scope: z.string().optional(),
  description: z.string().min(1, "Commit description is required"),
  body: z.string().optional(),
  taskId: z.string().uuid(),
  stepIndex: z.number().int().nonnegative(),
  commitHash: z.string().optional(),
  parentHash: z.string().optional(),
  timestamp: z.number().int().nonnegative().default(() => Date.now()),
});
export type SemanticCommitMeta = z.infer<typeof SemanticCommitMetaSchema>;

/**
 * Detailed patch model capturing modifications per file.
 */
export const FilePatchSchema = z.object({
  filePath: z.string().min(1, "File path is required"),
  oldPath: z.string().optional(),
  status: z.enum(["added", "modified", "deleted", "renamed"]),
  additions: z.number().int().nonnegative().default(0),
  deletions: z.number().int().nonnegative().default(0),
  diffHunk: z.string().default(""),
  hasConflict: z.boolean().default(false),
});
export type FilePatch = z.infer<typeof FilePatchSchema>;

/**
 * Complete diff summary between isolated worktree and base branch.
 */
export const DiffSummarySchema = z.object({
  baseCommitHash: z.string(),
  targetCommitHash: z.string(),
  files: z.array(FilePatchSchema).default([]),
  totalAdditions: z.number().int().nonnegative().default(0),
  totalDeletions: z.number().int().nonnegative().default(0),
  totalModifiedFiles: z.number().int().nonnegative().default(0),
  hasConflicts: z.boolean().default(false),
  conflictFiles: z.array(z.string()).default([]),
});
export type DiffSummary = z.infer<typeof DiffSummarySchema>;

/**
 * Deterministic rollback request dispatched on verification failure.
 */
export const RollbackRequestSchema = z.object({
  requestId: z.string().uuid().default(() => crypto.randomUUID()),
  taskId: z.string().uuid(),
  worktreePath: z.string(),
  targetCommitHash: z.string().min(7, "Valid target commit hash is required"),
  reason: z.string().min(1, "Rollback reason is required"),
  force: z.boolean().default(true),
  timestamp: z.number().int().nonnegative().default(() => Date.now()),
});
export type RollbackRequest = z.infer<typeof RollbackRequestSchema>;

/**
 * Human-in-the-loop audit gate for merging worktrees into user branches.
 */
export const MergeApprovalRequestSchema = z.object({
  requestId: z.string().uuid().default(() => crypto.randomUUID()),
  taskId: z.string().uuid(),
  targetBranch: z.string().default("main"),
  featureBranch: z.string(),
  worktreePath: z.string(),
  diffSummary: DiffSummarySchema,
  commitMessages: z.array(z.string()).default([]),
  status: z.enum(["pending", "approved", "rejected"]).default("pending"),
  approvedBy: z.string().optional(),
  rejectionReason: z.string().optional(),
  createdAt: z.number().int().nonnegative().default(() => Date.now()),
  resolvedAt: z.number().int().nonnegative().optional(),
});
export type MergeApprovalRequest = z.infer<typeof MergeApprovalRequestSchema>;
