import { EventEmitter } from "node:events";
import {
  PlanPatch,
  PlanPatchBatch,
  PlanPatchBatchSchema,
  TaskNode,
} from "@krypton/shared-types";
import { TaskTree } from "./task-tree.js";

export interface ReplannerConfig {
  autoRewireDependents?: boolean;
}

/**
 * Dynamic Error Replanner & DAG Restructuring Engine.
 * Intercepts task execution failures, pauses/blocks downstream dependents,
 * dynamically synthesizes remediation sub-tasks, and rewires the DAG.
 */
export class DynamicReplanner extends EventEmitter {
  private readonly autoRewire: boolean;

  constructor(config?: ReplannerConfig) {
    super();
    this.autoRewire = config?.autoRewireDependents ?? true;
  }

  /**
   * Evaluates a task failure, pauses downstream dependencies,
   * synthesizes an intermediate repair sub-task, and applies the batch patch to the tree.
   */
  public handleFailure(options: {
    tree: TaskTree;
    failedTaskId: string;
    errorDiagnostics: string;
    suggestedRemediationTitle?: string;
  }): PlanPatchBatch {
    const { tree, failedTaskId, errorDiagnostics } = options;
    const failedTask = tree.getTask(failedTaskId);
    if (!failedTask) {
      throw new Error(`Failed task '${failedTaskId}' not found in task tree`);
    }

    const patches: PlanPatch[] = [];

    // 1. Mark failed task
    patches.push({
      op: "markFailed",
      taskId: failedTaskId,
      reason: errorDiagnostics,
      suggestedRemediation: options.suggestedRemediationTitle,
    });

    // 2. Pause / block all direct and indirect downstream tasks
    const downstreamTasks = tree.getDownstreamDependents(failedTaskId);
    for (const downstream of downstreamTasks) {
      if (downstream.status === "pending" || downstream.status === "in_progress") {
        patches.push({
          op: "updateStatus",
          taskId: downstream.id,
          status: "blocked",
          metadataUpdates: {
            error: `Blocked by failure of upstream task '${failedTask.title}'`,
          },
        });
      }
    }

    // 3. Create remediation task node
    const remediationTaskId = crypto.randomUUID();
    const cleanDiag = errorDiagnostics.replace(/\r?\n/g, " ").trim();
    const shortDiag = cleanDiag.length > 60 ? cleanDiag.slice(0, 57) + "..." : cleanDiag;

    const remediationTitle =
      options.suggestedRemediationTitle ??
      `Fix failure in '${failedTask.title}': ${shortDiag}`;

    const remediationTaskNode: TaskNode = {
      id: remediationTaskId,
      title: remediationTitle,
      description: `Autonomous repair generated by DynamicReplanner.\nDiagnostics: ${errorDiagnostics}`,
      assignedAgentId: failedTask.assignedAgentId,
      dependsOn: [failedTaskId],
      status: "pending",
      subTaskIds: [],
      metadata: {
        retryCount: 0,
        custom: {
          isRemediation: true,
          targetFailedTaskId: failedTaskId,
        },
      },
      createdAt: Date.now(),
      updatedAt: Date.now(),
    };

    patches.push({
      op: "insertTask",
      task: remediationTaskNode,
      parentTaskId: undefined,
    });

    // 4. Rewire direct dependents to depend on the remediation task
    if (this.autoRewire) {
      for (const downstream of downstreamTasks) {
        if (downstream.dependsOn.includes(failedTaskId)) {
          const updatedDeps = downstream.dependsOn.map((id) =>
            id === failedTaskId ? remediationTaskId : id
          );
          patches.push({
            op: "updateDependencies",
            taskId: downstream.id,
            dependsOn: updatedDeps,
          });
        }
      }
    }

    const batch: PlanPatchBatch = PlanPatchBatchSchema.parse({
      batchId: crypto.randomUUID(),
      agentId: tree.agentId,
      treeId: tree.id,
      patches,
      timestamp: Date.now(),
    });

    // Apply patches to the tree
    tree.applyBatch(batch);

    // Emit plan restructured event
    this.emit("planRestructured", {
      treeId: tree.id,
      failedTaskId,
      remediationTaskId,
      blockedCount: downstreamTasks.length,
      batch,
    });

    return batch;
  }
}
